# Common database deployment and installation
version: '3.8'
services:

    mysql:
        platform: linux/x86_64
        image: mysql:5.7.31
        restart: always
        container_name: mysql57
        # Mount the data
        volumes:
            - ./mysql57/log:/var/log/mysql
            # Use a custom configuration file
            - ./my.cnf:/etc/mysql/my.cnf
            - ./mysql57/data:/var/lib/mysql
            # All sql in this directory will be initialized when it is first created
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        # Initialize database information
        environment:
            - "MYSQL_ROOT_PASSWORD=xxx"
            - "MYSQL_USER=root"
            - "MYSQL_PASS=xxx"
            - "MYSQL_DATABASE=news_crawl"
            - "MYSQL_PORT=3306"
            - "TZ=Europe/Istanbul"
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_general_ci',
            '--max_connections=3000'
        ]
        ports:
            - 3306:3306
        extra_hosts:
            - "host.localhost:127.0.0.1"
    redis:
        image: redis:6.0
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis/data:/data
            - ./redis.conf:/etc/redis/redis.conf
            - ./redis/log/redis.log:/logs/redis.log
        command: redis-server /etc/redis/redis.conf

