version: '3.8'
services:
    
    
#    # Logparser Settings Tool
#    crawl_scrapyd_logparser:
#         build: .
#         container_name: crawl_scrapyd_logparser
#         volumes:
#             - /Users/canahmetozguven/Desktop/dockerscrapydweb/NewsCrawl:/home/spider_workplace/TLNewsCrawl
#         working_dir: /home/spider_workplace/TLNewsCrawl/TLNewsSpider/scrapyd_server
#         command: logparser -dir ./logs

    # Basic crawler scheduling (Scrapyd) service
    crawl_scrapyd:
        build: .
        container_name: crawl_scrapyd
        expose: 
            - "6800"
        ports:
            - "6800:6800"
        volumes:
            - /Users/canahmetozguven/Desktop/dockerscrapydweb/NewsCrawl:/home/spider_workplace/TLNewsCrawl
        working_dir: /home/spider_workplace/TLNewsCrawl/TLNewsSpider/scrapyd_server/
        command: scrapyd --pidfile=

    # Crawler management platform (ScrapydWeb) service
    crawl_scrapyd_web:
        build: .
        depends_on:
            - crawl_scrapyd
#            - crawl_scrapyd_logparser
        container_name: crawl_scrapyd_web
        expose: 
            - "8000"
        ports:
            - "8000:8000"
        volumes:
            - /Users/canahmetozguven/Desktop/dockerscrapydweb/NewsCrawl:/home/spider_workplace/TLNewsCrawl

        working_dir: /home/spider_workplace/TLNewsCrawl/TLNewsSpider/scrapyd_web_manager/
        # Operations required to use an external database (otherwise the import package fails)
#        entrypoint: ["cp", "-f", "./vars.py", "/usr/local/lib/python3.7/site-packages/scrapydweb/vars.py"]
#        entrypoint: ["cp", "-r", "./scrapydweb_settings_v10.py", "/usr/local/lib/python3.7/site-packages/scrapydweb/"]
        command: /bin/bash -c "cp -f ./scrapydweb_settings_v10.py /usr/local/lib/python3.7/site-packages/scrapydweb/scrapydweb_settings_v10.py 
            && cp -f ./vars.py /usr/local/lib/python3.7/site-packages/scrapydweb/vars.py
            && scrapydweb"
networks:
  network1:
    name: my-network
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          ip_range: 172.18.5.0/24
          gateway: 172.18.0.1